/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 /Users/dervint/Desktop/For_Fun/maav-3d-web/maav-prototype-app/public/models/pfm1.glb 
*/

"use client"

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Mine(props) {
  const { nodes, materials } = useGLTF('/models/pfm1.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes['IARC_PFM-1_mine'].geometry} material={materials['Material.001']} />
    </group>
  )
}

useGLTF.preload('/models/pfm1.glb')
