// /*
// Auto-generated by: https://github.com/pmndrs/gltfjsx
// Command: npx gltfjsx@6.5.3 public/models/drone.glb 
// */

// import React from 'react'
// import { useGLTF } from '@react-three/drei'

// export function Drone(props) {
//   const { nodes, materials } = useGLTF('/models/maav-drone-model.glb')
//   return (
//     <group {...props} dispose={null}>
//       <mesh geometry={nodes.drone.geometry} material={nodes.drone.material} rotation={[Math.PI / 2, 0, 0]} />
//     </group>
//   )
// }

// useGLTF.preload('/models/maav-drone-model.glb')

/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/maav-drone-model.glb 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Drone(props) {
  const { nodes, materials } = useGLTF('/models/maav-drone-model.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Jetson_Xavier_NX_DevKit_LQ.geometry} material={materials['Material.015']} position={[-0.344, 1.703, 0]} scale={0.01} />
      <mesh geometry={nodes.body.geometry} material={materials['Material.001']} position={[0, 1.951, 0]} rotation={[-Math.PI, 0, -Math.PI]} scale={[-1, -0.029, -1]} />
      <mesh geometry={nodes.body001.geometry} material={materials['Material.003']} position={[0, 2, 0]} rotation={[-Math.PI, 0, -Math.PI]} scale={[-1, -0.029, -1]} />
      <mesh geometry={nodes.body002.geometry} material={materials['Material.002']} position={[0, 2, 0]} rotation={[-Math.PI, 0, -Math.PI]} scale={[-1, -0.029, -1]} />
      <mesh geometry={nodes.body003.geometry} material={nodes.body003.material} position={[0, 2, 0]} rotation={[-Math.PI, 0, -Math.PI]} scale={[-1, -0.029, -1]} />
      <mesh geometry={nodes.body004.geometry} material={nodes.body004.material} position={[0, 2, 0]} rotation={[-Math.PI, 0, -Math.PI]} scale={[-1, -0.029, -1]} />
      <mesh geometry={nodes.body005.geometry} material={nodes.body005.material} position={[0, 2, 0]} rotation={[-Math.PI, 0, -Math.PI]} scale={[-1, -0.029, -1]} />
      <mesh geometry={nodes.body006.geometry} material={nodes.body006.material} position={[0, 2, 0]} rotation={[-Math.PI, 0, -Math.PI]} scale={[-1, -0.029, -1]} />
      <mesh geometry={nodes['8x5R'].geometry} material={materials['Material.011']} position={[-3.009, 1.866, -1.639]} scale={0.018} />
      <mesh geometry={nodes['8x5R001'].geometry} material={materials['Material.011']} position={[-2.744, 1.866, 2.293]} scale={0.018} />
      <mesh geometry={nodes['8x5R002'].geometry} material={materials['Material.011']} position={[2.782, 1.866, 2.198]} scale={0.018} />
      <mesh geometry={nodes['8x5R003'].geometry} material={materials['Material.011']} position={[2.921, 1.866, -1.988]} scale={0.018} />
      <group position={[-3.05, -0.105, -1.617]} rotation={[-Math.PI, 1.012, -Math.PI]} scale={[-0.341, -0.03, -0.341]}>
        <mesh geometry={nodes.Cube027.geometry} material={materials['Material.009']} />
        <mesh geometry={nodes.Cube027_1.geometry} material={materials['Material.004']} />
        <mesh geometry={nodes.Cube027_2.geometry} material={materials['Material.010']} />
      </group>
      <group position={[-2.744, -0.105, 2.293]} rotation={[-Math.PI, 0, -Math.PI]} scale={[-0.341, -0.03, -0.341]}>
        <mesh geometry={nodes.Cube024.geometry} material={materials['Material.009']} />
        <mesh geometry={nodes.Cube024_1.geometry} material={materials['Material.004']} />
        <mesh geometry={nodes.Cube024_2.geometry} material={materials['Material.010']} />
      </group>
      <group position={[2.921, -0.105, -1.988]} rotation={[0, -0.125, 0]} scale={[-0.341, -0.03, -0.341]}>
        <mesh geometry={nodes.Cube028.geometry} material={materials['Material.009']} />
        <mesh geometry={nodes.Cube028_1.geometry} material={materials['Material.004']} />
        <mesh geometry={nodes.Cube028_2.geometry} material={materials['Material.010']} />
      </group>
      <group position={[2.782, -0.105, 2.198]} rotation={[0, -1.254, 0]} scale={[-0.341, -0.03, -0.341]}>
        <mesh geometry={nodes.Cube029.geometry} material={materials['Material.009']} />
        <mesh geometry={nodes.Cube029_1.geometry} material={materials['Material.004']} />
        <mesh geometry={nodes.Cube029_2.geometry} material={materials['Material.010']} />
      </group>
    </group>
  )
}

useGLTF.preload('/models/maav-drone-model.glb')

