/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Enhanced with realistic materials and carbon fiber texture
*/

import React, { useMemo } from 'react'
import { useGLTF } from '@react-three/drei'
import * as THREE from 'three'

// Create procedural carbon fiber texture
function createCarbonFiberTexture() {
  const canvas = document.createElement('canvas')
  const size = 128
  canvas.width = size
  canvas.height = size
  const ctx = canvas.getContext('2d')

  // Base dark color
  ctx.fillStyle = '#1a1a1a'
  ctx.fillRect(0, 0, size, size)

  // Create carbon fiber weave pattern
  const weaveSize = 8

  for (let y = 0; y < size; y += weaveSize) {
    for (let x = 0; x < size; x += weaveSize) {
      const isEven = ((x / weaveSize) + (y / weaveSize)) % 2 === 0

      // Draw diagonal weave pattern
      ctx.fillStyle = isEven ? '#252525' : '#1a1a1a'
      ctx.fillRect(x, y, weaveSize, weaveSize)

      // Add highlight lines for weave effect
      ctx.strokeStyle = isEven ? '#303030' : '#222222'
      ctx.lineWidth = 1
      ctx.beginPath()
      if (isEven) {
        ctx.moveTo(x, y)
        ctx.lineTo(x + weaveSize, y + weaveSize)
      } else {
        ctx.moveTo(x + weaveSize, y)
        ctx.lineTo(x, y + weaveSize)
      }
      ctx.stroke()

      // Add subtle shine
      ctx.fillStyle = isEven ? 'rgba(255,255,255,0.03)' : 'rgba(0,0,0,0.02)'
      ctx.fillRect(x, y, weaveSize / 2, weaveSize / 2)
    }
  }

  const texture = new THREE.CanvasTexture(canvas)
  texture.wrapS = THREE.RepeatWrapping
  texture.wrapT = THREE.RepeatWrapping
  texture.repeat.set(4, 4)
  return texture
}

// Create normal map for carbon fiber depth
function createCarbonFiberNormal() {
  const canvas = document.createElement('canvas')
  const size = 128
  canvas.width = size
  canvas.height = size
  const ctx = canvas.getContext('2d')

  // Neutral normal map base (128, 128, 255)
  ctx.fillStyle = 'rgb(128, 128, 255)'
  ctx.fillRect(0, 0, size, size)

  const weaveSize = 8

  for (let y = 0; y < size; y += weaveSize) {
    for (let x = 0; x < size; x += weaveSize) {
      const isEven = ((x / weaveSize) + (y / weaveSize)) % 2 === 0

      // Create depth variation for weave
      if (isEven) {
        ctx.fillStyle = 'rgb(140, 140, 255)' // Slight bump up
      } else {
        ctx.fillStyle = 'rgb(116, 116, 255)' // Slight indent
      }
      ctx.fillRect(x + 1, y + 1, weaveSize - 2, weaveSize - 2)
    }
  }

  const texture = new THREE.CanvasTexture(canvas)
  texture.wrapS = THREE.RepeatWrapping
  texture.wrapT = THREE.RepeatWrapping
  texture.repeat.set(4, 4)
  return texture
}

export function Drone(props) {
  const { nodes, materials } = useGLTF('/models/maav-drone-model.glb')

  // Create realistic materials with carbon fiber texture
  const droneMateria = useMemo(() => {
    const carbonTexture = createCarbonFiberTexture()
    const carbonNormal = createCarbonFiberNormal()

    // Jetson Xavier NX - dark green PCB with gold traces look
    const jetsonMaterial = new THREE.MeshStandardMaterial({
      color: '#1a3d1a',
      metalness: 0.3,
      roughness: 0.7,
      envMapIntensity: 0.8,
    })

    // Carbon fiber frame - with actual texture
    const carbonFiberMaterial = new THREE.MeshStandardMaterial({
      map: carbonTexture,
      normalMap: carbonNormal,
      normalScale: new THREE.Vector2(0.3, 0.3),
      metalness: 0.5,
      roughness: 0.3,
      envMapIntensity: 1.4,
    })

    // Frame accent - carbon fiber variant
    const frameAccentMaterial = new THREE.MeshStandardMaterial({
      map: carbonTexture.clone(),
      normalMap: carbonNormal.clone(),
      normalScale: new THREE.Vector2(0.2, 0.2),
      metalness: 0.4,
      roughness: 0.35,
      envMapIntensity: 1.2,
    })

    // Shell/cover - plain matte black (no texture)
    const shellMaterial = new THREE.MeshStandardMaterial({
      color: '#0d0d0d',
      metalness: 0.1,
      roughness: 0.6,
      envMapIntensity: 0.5,
    })

    // Propellers - semi-gloss black plastic
    const propellerMaterial = new THREE.MeshStandardMaterial({
      color: '#1a1a1a',
      metalness: 0.0,
      roughness: 0.3,
      envMapIntensity: 0.6,
    })

    // Motors - brushed aluminum
    const motorMetalMaterial = new THREE.MeshStandardMaterial({
      color: '#c0c0c0',
      metalness: 0.9,
      roughness: 0.25,
      envMapIntensity: 1.5,
    })

    // Motor base - dark anodized aluminum
    const motorBaseMaterial = new THREE.MeshStandardMaterial({
      color: '#2d2d2d',
      metalness: 0.85,
      roughness: 0.3,
      envMapIntensity: 1.2,
    })

    // Motor accents - copper windings hint
    const motorAccentMaterial = new THREE.MeshStandardMaterial({
      color: '#b87333',
      metalness: 0.8,
      roughness: 0.4,
      envMapIntensity: 1.0,
    })

    return {
      jetson: jetsonMaterial,
      carbonFiber: carbonFiberMaterial,
      frameAccent: frameAccentMaterial,
      shell: shellMaterial,
      propeller: propellerMaterial,
      motorMetal: motorMetalMaterial,
      motorBase: motorBaseMaterial,
      motorAccent: motorAccentMaterial,
    }
  }, [])

  return (
    <group {...props} dispose={null}>
      {/* Jetson Xavier NX */}
      <mesh
        geometry={nodes.Jetson_Xavier_NX_DevKit_LQ.geometry}
        material={droneMateria.jetson}
        position={[-0.344, 1.703, 0]}
        scale={0.01}
      />

      {/* Main body/frame - carbon fiber */}
      <mesh
        geometry={nodes.body.geometry}
        material={droneMateria.carbonFiber}
        position={[0, 1.951, 0]}
        rotation={[-Math.PI, 0, -Math.PI]}
        scale={[-1, -0.029, -1]}
      />
      <mesh
        geometry={nodes.body001.geometry}
        material={droneMateria.frameAccent}
        position={[0, 2, 0]}
        rotation={[-Math.PI, 0, -Math.PI]}
        scale={[-1, -0.029, -1]}
      />
      <mesh
        geometry={nodes.body002.geometry}
        material={droneMateria.carbonFiber}
        position={[0, 2, 0]}
        rotation={[-Math.PI, 0, -Math.PI]}
        scale={[-1, -0.029, -1]}
      />

      {/* Shell/covers */}
      <mesh
        geometry={nodes.body003.geometry}
        material={droneMateria.shell}
        position={[0, 2, 0]}
        rotation={[-Math.PI, 0, -Math.PI]}
        scale={[-1, -0.029, -1]}
      />
      <mesh
        geometry={nodes.body004.geometry}
        material={droneMateria.shell}
        position={[0, 2, 0]}
        rotation={[-Math.PI, 0, -Math.PI]}
        scale={[-1, -0.029, -1]}
      />
      <mesh
        geometry={nodes.body005.geometry}
        material={droneMateria.shell}
        position={[0, 2, 0]}
        rotation={[-Math.PI, 0, -Math.PI]}
        scale={[-1, -0.029, -1]}
      />
      <mesh
        geometry={nodes.body006.geometry}
        material={droneMateria.shell}
        position={[0, 2, 0]}
        rotation={[-Math.PI, 0, -Math.PI]}
        scale={[-1, -0.029, -1]}
      />

      {/* Propellers */}
      <mesh
        geometry={nodes['8x5R'].geometry}
        material={droneMateria.propeller}
        position={[-3.009, 1.866, -1.639]}
        scale={0.018}
      />
      <mesh
        geometry={nodes['8x5R001'].geometry}
        material={droneMateria.propeller}
        position={[-2.744, 1.866, 2.293]}
        scale={0.018}
      />
      <mesh
        geometry={nodes['8x5R002'].geometry}
        material={droneMateria.propeller}
        position={[2.782, 1.866, 2.198]}
        scale={0.018}
      />
      <mesh
        geometry={nodes['8x5R003'].geometry}
        material={droneMateria.propeller}
        position={[2.921, 1.866, -1.988]}
        scale={0.018}
      />

      {/* Motors */}
      <group position={[-3.05, -0.105, -1.617]} rotation={[-Math.PI, 1.012, -Math.PI]} scale={[-0.341, -0.03, -0.341]}>
        <mesh geometry={nodes.Cube027.geometry} material={droneMateria.motorMetal} />
        <mesh geometry={nodes.Cube027_1.geometry} material={droneMateria.motorBase} />
        <mesh geometry={nodes.Cube027_2.geometry} material={droneMateria.motorAccent} />
      </group>
      <group position={[-2.744, -0.105, 2.293]} rotation={[-Math.PI, 0, -Math.PI]} scale={[-0.341, -0.03, -0.341]}>
        <mesh geometry={nodes.Cube024.geometry} material={droneMateria.motorMetal} />
        <mesh geometry={nodes.Cube024_1.geometry} material={droneMateria.motorBase} />
        <mesh geometry={nodes.Cube024_2.geometry} material={droneMateria.motorAccent} />
      </group>
      <group position={[2.921, -0.105, -1.988]} rotation={[0, -0.125, 0]} scale={[-0.341, -0.03, -0.341]}>
        <mesh geometry={nodes.Cube028.geometry} material={droneMateria.motorMetal} />
        <mesh geometry={nodes.Cube028_1.geometry} material={droneMateria.motorBase} />
        <mesh geometry={nodes.Cube028_2.geometry} material={droneMateria.motorAccent} />
      </group>
      <group position={[2.782, -0.105, 2.198]} rotation={[0, -1.254, 0]} scale={[-0.341, -0.03, -0.341]}>
        <mesh geometry={nodes.Cube029.geometry} material={droneMateria.motorMetal} />
        <mesh geometry={nodes.Cube029_1.geometry} material={droneMateria.motorBase} />
        <mesh geometry={nodes.Cube029_2.geometry} material={droneMateria.motorAccent} />
      </group>
    </group>
  )
}

useGLTF.preload('/models/maav-drone-model.glb')
