/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/drone.glb 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Drone(props) {
  const { nodes, materials } = useGLTF('/models/drone.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.drone.geometry} material={nodes.drone.material} rotation={[Math.PI / 2, 0, 0]} />
    </group>
  )
}

useGLTF.preload('/models/drone.glb')
